version: "3"
services:
  db:
    image: mysql:8.0
    # コンテナ名を明示的に指定する
    container_name: mysql-db-container
    # ホスト名を明示的に指定する
    hostname: db-server
    volumes:
      - mysql-db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      #- MYSQL_DATABASE=${DB_NAME}
      #- MYSQL_USER=${DB_USER}
      #- MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    ports:
      - ${DB_PORT}:3306

volumes:
  mysql-db-store:
